### PR TITLE
mavgen_cpp11: Solve path problem in import

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by kartikmohta** [comment]
This has already been fixed in upstream (https://github.com/ArduPilot/pymavlink/commit/b4f9dda8138a0bea399df9e9e9f13ec80c902113)

**Comment by amilcarlucas** [comment]
There is another pull requests that merges all upstream changes up-to 2.2.8 release

**Comment by amilcarlucas** [comment]
This PR can be closed now, These changes are already in the master branch

**Comment by amilcarlucas** [comment]
@LorenzMeier this PR can be closed now, These changes are already in the master branch

**Comment by LorenzMeier** [comment]
Thanks!

**Pull request closed without merging**
