### PR TITLE
merge upstream ardupilot changes

### PR DESCRIPTION
**Pull request by amilcarlucas**
Merge in changes from pymavlink 2.2.5 though 2.2.8

### CODE REVIEW

**Comment by kartikmohta** [comment]
@amilcarlucas Why did you do a rebase instead of a merge to pull in changes from upstream?

**Comment by amilcarlucas** [comment]
@kartikmohta Thanks for pointing that out. I corrected that now.

**Comment by amilcarlucas** [comment]
@dagar, @DonLakeFlyer can you review this ?

**Comment by DonLakeFlyer** [comment]
I don't know anything about the generator code. So can't help here.

**Comment by amilcarlucas** [comment]
Thanks anyway Don.

**Comment by amilcarlucas** [comment]
These have been approved and merged upstream. And are also approved downstream (here).
When will it get merged ???

**Pull request merged**
